### ISSUE TITLE
No events firing

### ISSUE THREAD

**Issue by sebytab** [gampleman/elm-mapbox#2]
Hi! I'm building a SPA with Elm 0.19 where I'm using 2 js plugins: Swiper and Mapbox.
I wanted to simplify the integration through custom-elements so I found this amazing plugin! 
I successfully tried the examples but when I try to integrate plugin in one view it renders correctly but no events are fired. Attributes like maxZoom are working correctly.
I have followed R. Feldman SPA example (https://github.com/rtfeldman/elm-spa-example). All page messages are correctly mapped in main view except mapbox-plugin messages.
At runtime there are correctly 2 attached map-element events (click, mouseOver) and if I manually add one it works correctly.

**Comment by gampleman** [comment]
Sorry I did not see this issue until now.

There is not enough information here to guess what the issue may be. Can you reproduce the issue in Ellie? Also worth noting is what browser are you testing on? Any polyfills etc?
