### ISSUE TITLE
Layer.isVisible error at runtime

### ISSUE THREAD

**Issue by maxf** [gampleman/elm-mapbox#40]
Setting `Layer.visible (E.bool True)` on any layer compiles, but gives a runtime error:
```
Error: layers[1].layout.visibility: expected one of [visible, none], ["case",true,"visible","none"] found
```

**Comment by pjsier** [comment]
According to the current [style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-background-visibility) `visibility` doesn't support data-driven styling, and the current setup is using a `case` expression to set the values. I can put in a PR to fix this if that works @gampleman

**Comment by gampleman** [comment]
I think that will be necessary, but this will be a breaking change. TBH I’m not really sure what the use case for the visibility attribute is...

**Comment by pjsier** [comment]
Makes sense! In my experience it's been useful for toggling between layers without removing them entirely

**Comment by gampleman** [comment]
Is that for performance reasons? Otherwise I don't really see the difference between hiding and removing...

**Comment by pjsier** [comment]
I think it might be a little better performance wise, and if you make the layer invisible instead of removing it you can still query it with `queryRenderedFeatures`

**Comment by gampleman** [comment]
Interesting. I’m happy to accept a PR for this, although I may batch releasing it with some more breaking changes.
