### ISSUE TITLE
Subscribing to Changes

### ISSUE THREAD

**Issue by andre-dietrich** [gampleman/elm-mapbox#52]
Hi, great library! I wanted to ask, what is the best way to subscribe to changes at the map? For example if I would like to change the URL accordingly, when scrolling? I mean, getting the new bounding boxes and the zoom factor. At the moment I use subscriptions on `mousemove` and check, if the center position has changed, but that does not work for scrolling... I guess there is a better way...

Thanks in advance...

**Comment by gampleman** [comment]
Hi @andre-dietrich, I think subscribing to the `move` event should do the trick. I'm in the process of improving how the events work to make this a bit more convenient in the future.
