### ISSUE TITLE
README pointing to different repo for Example01

### ISSUE THREAD

**Issue by PixelPartner** [gampleman/elm-mapbox#74]
It seems like you forgot to change the link URL when you copied content over from `elm-geospatial` at [the Example section](https://github.com/gampleman/elm-mapbox/blob/master/README.md#example)

**Comment by gampleman** [comment]
This is on purpose, as there is a bit of a walkthrough using both packages there: https://github.com/gampleman/elm-geospatial/tree/master/examples
